// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB874gEPQquAFchX7kYGSA0TGPWEGj5ecs',
    appId: '1:265992674926:web:778f36fc3777e444ca507f',
    messagingSenderId: '265992674926',
    projectId: 'edusphere-f6db2',
    authDomain: 'edusphere-f6db2.firebaseapp.com',
    storageBucket: 'edusphere-f6db2.firebasestorage.app',
    measurementId: 'G-VL08ZMNM87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JjOwcM1KqjfpLho8ddzgOv0pb5tXiO0',
    appId: '1:265992674926:android:641d766f67c9445dca507f',
    messagingSenderId: '265992674926',
    projectId: 'edusphere-f6db2',
    storageBucket: 'edusphere-f6db2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWmVNsQ4em049gSXm4Pk8PtI0Gf_Xn2I',
    appId: '1:265992674926:ios:ac3a5928b540df65ca507f',
    messagingSenderId: '265992674926',
    projectId: 'edusphere-f6db2',
    storageBucket: 'edusphere-f6db2.firebasestorage.app',
    iosBundleId: 'com.example.edushpere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlWmVNsQ4em049gSXm4Pk8PtI0Gf_Xn2I',
    appId: '1:265992674926:ios:ac3a5928b540df65ca507f',
    messagingSenderId: '265992674926',
    projectId: 'edusphere-f6db2',
    storageBucket: 'edusphere-f6db2.firebasestorage.app',
    iosBundleId: 'com.example.edushpere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB874gEPQquAFchX7kYGSA0TGPWEGj5ecs',
    appId: '1:265992674926:web:ce14fafedaa6c0f1ca507f',
    messagingSenderId: '265992674926',
    projectId: 'edusphere-f6db2',
    authDomain: 'edusphere-f6db2.firebaseapp.com',
    storageBucket: 'edusphere-f6db2.firebasestorage.app',
    measurementId: 'G-692QT0RDJ5',
  );
}
